# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appsyncgen < Formula
  desc ""
  homepage "https://github.com/kopkunka55/appsyncgen"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kopkunka55/appsyncgen/releases/download/v1.0.2/appsyncgen_darwin_arm64.tar.gz"
      sha256 "5dd0b6311209510832eddf6dd6e4874726def4f8428df7cced5ed27c6309e724"

      def install
        bin.install "appsyncgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kopkunka55/appsyncgen/releases/download/v1.0.2/appsyncgen_darwin_x86_64.tar.gz"
      sha256 "b3ac9afcbe8d1321776a0c58c54b888987d886d2d277a53210e5807775b81fd1"

      def install
        bin.install "appsyncgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kopkunka55/appsyncgen/releases/download/v1.0.2/appsyncgen_linux_arm64.tar.gz"
      sha256 "6afd381b2df9f8a73e4bef3b2adbcbeff34beb7e2628b6fae545bac91b29d912"

      def install
        bin.install "appsyncgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kopkunka55/appsyncgen/releases/download/v1.0.2/appsyncgen_linux_x86_64.tar.gz"
      sha256 "2401cfb3c37d58ec7e251646240c6ea4e3d0ad9717e414b1c365ad29f785206e"

      def install
        bin.install "appsyncgen"
      end
    end
  end
end
